# Generated by Django 3.0.5 on 2020-12-02 07:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Layer',
            fields=[
                ('record_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='finance.Record')),
            ],
            options={
                'verbose_name': '按钮弹出对话框',
                'verbose_name_plural': '按钮弹出对话框',
            },
            bases=('finance.record',),
        ),
    ]
