# Generated by Django 3.2.2 on 2021-05-20 00:47

from django.db import migrations, models
import rate.fields


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RateModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f1', rate.fields.RateField(verbose_name='评分1')),
                ('f2', rate.fields.RateField(verbose_name='评分2')),
                ('f3', rate.fields.RateField(default=3.5, verbose_name='评分3')),
            ],
            options={
                'verbose_name': 'Rate评分',
                'verbose_name_plural': 'Rate评分',
            },
        ),
    ]
